name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
        
      - name: Download
        shell: bash
        run: |
          git clone https://github.com/Silverlan/tmp_pr_chromium_wrapper_ci.git tmp_pr_chromium_wrapper_ci
        
      - name: Download
        shell: bash
        run: |
          wget https://cef-builds.spotifycdn.com/cef_binary_106.1.0%2Bg30ad805%2Bchromium-106.0.5249.119_linux64_minimal.tar.bz2
          tar -xvf cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal.tar.bz2
        
      - name: Build
        shell: bash
        run: |
          cd "cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal"
          cmake -G "Unix Makefiles"
          cmake --build ./ --verbose
          
      - name: Build2
        shell: bash
        run: |
          cd tmp_pr_chromium_wrapper_ci
          cmake -G "Unix Makefiles" -DDEPENDENCY_CHROMIUM_INCLUDE="../cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal/" -DDEPENDENCY_CHROMIUM_LIBRARY="../cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal/Release/libcef.so" -DDEPENDENCY_LIBCEF_DLL_WRAPPER_LIBRARY="../cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal/libcef_dll_wrapper/libcef_dll_wrapper.a" -DDEPENDENCY_PR_CHROMIUM_WRAPPER_LIBRARY="./libpr_chromium_wrapper.so"
          cmake --build ./ --verbose

      - name: Build3
        shell: bash
        run: |
          cmake -G "Unix Makefiles"
          cmake --build ./ --verbose
          
      - name: Copy libs
        shell: bash
        run: |
          rsync --mkpath ./cef_binary_106.1.0+g30ad805+chromium-106.0.5249.119_linux64_minimal/Release/libcef.so ./
          rsync --mkpath ./libpr_chromium_wrapper.so ./
          rsync --mkpath ./subprocess/pr_chromium_subprocess ./
          
      - uses: mxschmitt/action-tmate@v3
        name: CI
